### ISSUE TITLE
Startup File and New Files

### ISSUE THREAD

**Issue by Skulltulla** [nutti/Screencast-Keys#14]
**System Information**
  
* OS: Windows 10 Home x64
* Blender version: 2.81.16
* Add-on version: 3.0  (2f46722)

**Expected behavior**  
- Screencast Keys will remain functional after creating a new file (e.g. File > New > General).
- Screencast Keys will remain enabled after enabling it, saving the startup file (File > Defaults > Save Startup File), and restarting Blender.

**Description about the bug**  
- After Screencast Keys is enabled, it will continue to function normally until a new file is made. After a new file is made (e.g. File > New > General), ScreencastKeys will remain enabled, but it's won't display the keys. You can disable it and enable it again to make it work.
- After Screencast Keys is enabled and the Startup file is saved (File > Default > Save Startup File), it will not be enabled when Blender is restarted.

**Screenshots/Files** [Optional]  
NA

**Additional comments** [Optional]
NA

**Comment by nutti** [comment]
@Skulltulla 

Nice catch! And, sorry for my late reply.
This issue was reproduced in my environment.
I will look into this issue more detail.
Thanks.

**Comment by nutti** [comment]
This bug is now fixed.

@Skulltulla 

Thanks for your great feedback!

**Comment by L-Travieso** [comment]
this bug is back in 2.83.1 :(

-     Screencast Keys will remain functional after creating a new file (e.g. File > New > General).
-     Screencast Keys will remain enabled after enabling it, saving the startup file (File > Defaults > Save Startup File), and restarting Blender.
