### ISSUE TITLE
[blender 3.4.0] mouse wheel UP/DOWN on the timeline view seems to be lagging.

### ISSUE THREAD

**Issue by niuin** [nutti/Screencast-Keys#143]
### System Information  
* OS: Windows 10 Pro
* Blender version: 3.4.0
* Add-on version: 3.8.0

### Expected behavior
Smooth operation on the timeline view

### Description about the bug**
I have enabled Screencast-keys in Blender 3.4.0.
mouse wheel UP/DOWN on the timeline view seems to be lagging.

### Screenshots/Files [Optional]  
![sckeys](https://user-images.githubusercontent.com/868060/207426026-967ae480-a21f-4360-b6db-92b401c416cc.jpg)

**Comment by nutti** [comment]
This seems the Blender's issue.
The execution time of `blf.dimension` is very slow when you zoom in/out on Dope Sheet Editor.

I submitted the issue to the D.B.O.
https://developer.blender.org/T103210

**Comment by Viclio** [comment]
I have this issue also. For my part I noticed it in the node editor. Panning is ok, zooming with the mouse wheel is horrendous. Zooming using crtl+middle mouse is smooth, but then there's a lag upon release.

**Comment by nutti** [comment]
@Viclio 

The reason of this issue has already investigated.
This issue can not be solved from this add-on only.
If you want to haste, I recommend you to mention at [D.B.O](https://developer.blender.org/T103210)

**Comment by nutti** [comment]
@niuin 

As you may know, this issue is now fixed in the recent released version.
So, I will close this issue for now.

**Comment by 161803393** [comment]
Is this problem solved? I've tried screencast 3.8 with blender 3.4 / 3.4.1 / 3.5a, but  I'm still having problems.
