### ISSUE TITLE
enabling screencast keys makes blender text overlays bounce all over the place

### ISSUE THREAD

**Issue by 3diuk** [nutti/Screencast-Keys#33]
**System Information**
Operating system: Windows-10-10.0.18362-SP0 64 Bits
Graphics card: GeForce GTX 1070/PCIe/SSE2 NVIDIA Corporation 4.5.0 NVIDIA 456.38

**Blender Version**
Broken: version: 2.91.0 Alpha, branch: master, commit date: 2020-10-13 22:29, hash: `rB2cc7be3e4907`

text info and statisctics overlays (to left) are bouncing around all over the place if screencast keys is enabled.  Check out the attached video.

[drawing bug.zip](https://github.com/nutti/Screencast-Keys/files/5375328/drawing.bug.zip)

**Comment by nutti** [comment]
@3diuk 

Thanks, this bug is fixed now.

**Comment by 3diuk** [comment]
awesome!

**Comment by 3diuk** [comment]
Hi bug is still there if origin is window rather than window.

**Comment by nutti** [comment]
@3diuk 

The main reason of this issue is a lack of API in blf module.
If there is a way to get original font size, this issue will be fixed.

Do you have any ideas to realize this?
I also posted the question to blender.stackexchange.com.

https://blender.stackexchange.com/questions/198727/get-font-size-of-blf-module

**Comment by 3diuk** [comment]
I'm not sure.  You might have more luck getting an answer at:

https://blender.chat/channel/python

**Comment by 3diuk** [comment]
unrelated question.  Do you know how to get information about what the mouse is hovered over?  I need to find the area, panel type, parameter/property id/name, or any other UI element identifiers.

**Comment by nutti** [comment]
@3diuk 

Thanks.
I will post the question later.
If it is difficult to solve this issue, we will need to downgrade this add-on.

>  Do you know how to get information about what the mouse is hovered over? I need to find the area, panel type, parameter/property id/name, or any other UI element identifiers.

This should be discussed in other place.
I think you can use `area.x` or `area.width` for finding area, as well as `region.x` or `region.width` for region to find area and region where mouse is placed.
But I don't have any ideas to get parameter/prop_id/name.

**Comment by nutti** [comment]
BTW, this bug is also found in Shortcut VUr.
Perhaps, we should report this to Blender developers.
I doubt if this is a problem of Blender itself.

**Comment by nutti** [comment]
Reverted old commit.
I think we should simple program which reproduces this phenomena, and direct to D.B.O.

**Comment by nutti** [comment]
@3diuk 

I could easily reproduce this bug by below simple add-on.

https://gist.github.com/nutti/6d06ee1ab43cc9b6d02e14988f62ba3b

The point is here. If we change blf module font size, we can see same issue.

https://gist.github.com/nutti/6d06ee1ab43cc9b6d02e14988f62ba3b#file-blf_bug-py-L23-L25

**Comment by 3diuk** [comment]
yes definitely, I think you should report the bug ASAP.

**Comment by nutti** [comment]
I posted the bug report to D.B.O.

https://developer.blender.org/T81757

If you have any additional information, feel free to comment there.

**Comment by 3diuk** [comment]
caused by this perhaps?

https://developer.blender.org/D9107

**Comment by nutti** [comment]
@3diuk 

Yeah, I also think this seems to cause the issue.

**Comment by nutti** [comment]
This issue now fixed in Blender 2.91 Beta (b0f34eee30c4), so I will close this issue.
If the issue still exists, please reopen this issue again.
Thanks.
